services:
  web_test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - FLASK_ENV=testing
      - SQLALCHEMY_DATABASE_URI=postgresql://user:password@db_test:5432/flask_db_test
    depends_on:
      - db_test
    networks:
      - test_network

  db_test:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flask_db_test
    ports:
      - "5433:5432"  
    networks:
      - test_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d flask_db_test"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  test_network:
    driver: bridge